name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      altertable:
        image: ghcr.io/altertable-ai/altertable-mock:latest
        ports:
          - 15000:15000
        env:
          ALTERTABLE_MOCK_USERS: testuser:testpass
        options: >-
          --health-cmd "exit 0"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
          --health-start-period 10s

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run tests
        run: ./vendor/bin/phpunit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHPCS
        run: ./vendor/bin/phpcs
